### ISSUE TITLE
No proper documentation 

### ISSUE THREAD

**Issue by PiyushYadav007** [swadmahfuz/Certificate-Verification-System#1]
Please provide a proper documentation on how to use this template.

**Comment by swadmahfuz** [comment]
> 

Hi there! Thanks for opening this issue. Since it's a project in progress and there will be more feature added to it over time, I haven't gotten the time to make the documentation yet. If you want to check how it works, clone the repository, register an account and login to check it the features. 

Registration url: "/register" 
Login url: "/login" 

Stay tuned for the documentation and let me know if you any help running the project.

**Comment by PiyushYadav007** [comment]
thanks for your reply but it didn't work how i expected

**Comment by swadmahfuz** [comment]
Could you get it to work?

**Comment by PiyushYadav007** [comment]
Yeh it worked but not how i expected
